# TensorFlow

https://www.tensorflow.org/

https://www.tensorflow.org/guide/tensor

>[TensorFlow](#scrollTo=QpYeAL8aonn8)

>>[Creating Tensors](#scrollTo=mjESz3TkonoB)

>>[Rank / Degree of Tensors](#scrollTo=qfhhTQrTonoC)

>>[Shape of Tensors](#scrollTo=yqbB-3LEqbcA)

>>[Changing Shape](#scrollTo=mStUGXOVq1tr)

>>[Types of Tensors](#scrollTo=PQrgkirzt-P0)

>>[Evaluating Tensors](#scrollTo=9bSXY2oGuX4M)



In [2]:
%tensorflow_version 2.x # this line is not required unless you are in a notebook

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.


In [3]:
import tensorflow as tf
print(tf.version) # make sure the version is 2.x

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.7/dist-packages/tensorflow/_api/v2/version/__init__.py'>


## Creating Tensors

- Scalar values mean 1 value
- Vector value mean more than 1 value

In [4]:
string = tf.Variable("This is a string", tf.string) # It stores 1 string
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)

## Rank / Degree of Tensors

Another word for rank is degree. These terms simply mean the number of dimensions involved in the tensor. What we created above is a tensor of rank 0, also known as scalar. 

Now we'll create some tensors of higher degrees / ranks. 

In [5]:
rank1_tensor = tf.Variable(["Test"], tf.string) # rank 1 tensor because there's only 1 list
rank2_tensor = tf.Variable([["test", "ok", "okay"], ["test", "yes", "yeah"]], tf.string) # rank 2 tensor because we have a list inside a list

To determine the rank of a tensor we can call the .rank method

In [6]:
tf.rank(rank2_tensor) # numpy= will tell you the rank

<tf.Tensor: shape=(), dtype=int32, numpy=2>

## Shape of Tensors

The shape is the amount of elements that exist in each dimension.

In [7]:
rank2_tensor.shape

TensorShape([2, 3])

## Changing Shape

The number of elements of a tensor is the product of the sizes of all its shapes. There are often many shapes that have the same number of elements, making it convenient to change the shape of a tensor.

The example below shows how to change the shape of a tensor.

In [8]:
tensor1 = tf.ones([1,2,3]) # tf.ones() creates a shape [1,2,3] tensor full of ones
tensor2 = tf.reshape(tensor1, [2,3,1]) # reshape existing data to shape [2,3,1]
tensor3 = tf.reshape(tensor2, [3, -1]) # -1 tells the tensor to calculate the size of the dimension in that place
                                       # this will reshape the tensor to [3,2]

# The number of elements in the reshaped tensor MUST match the number in the original

In [9]:
print(tensor1)
print(tensor2)
print(tensor3)
# notice the changes in shape

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [14]:
# more reshaping

t = tf.zeros([5,5,5,5])
t = tf.reshape(t, [625]) # reshaping to a flat
t = tf.reshape(t, [125, -1]) # -1 tells tensorflow to calculate for you
print(t)


tf.Tensor(
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]

## Types of Tensors

These are the most common used ones:
* Variable
* Constant
* Placeholder
* SparseTensor

With the exception of `Variable`, all of the tensors are immutable, meaning that their value may not change during execution. 

## Evaluating Tensors

There will be times when we need to evaluate a tensor. In other words, get its value. Since tensors represent a partially complete computation we will sometimes need to run what's called a **session** to evaluate the tensor. 

The simplest way if below:

In [12]:
with tf.session() as sess: # creates a session using the default graph
  tensor.eval() # tensor will of course will be the name of your tensor

AttributeError: ignored